title: "Fundamentals of Arthroscopic Surgery Training and beyond: a reinforcement learning exploration and benchmark"
authors: Ami Beuret, Ivan Ovinnikov, Flavia Cavaliere and Joachim M. Buhmann
theme: jekyll-theme-cayman
