title: "Fundamentals of Arthroscopic Surgery Training and beyond: a reinforcement learning exploration and benchmark"
authors: Ami Beuret, Ivan Ovinnikov, Flavia Cavaliere and Joachim M. Buhmann
paper_url: https://doi.org/10.1007/s11548-024-03116-z 
theme: jekyll-theme-cayman
