behaviors:
  ImageCentering:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.01
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.15
        encoding_size: 128
        learning_rate: 0.0003

    keep_checkpoints: 15
    init_path: null
    checkpoint_interval: 5000000
    max_steps: 40000000
    time_horizon: 1024
    summary_freq: 2000
    threaded: false
    framework: tensorflow
